### PR TITLE
Making the knowledge base persistent using mongodb

### PR DESCRIPTION
**Pull request by cdondrup**
This adds the ability to start the knowledge base with the parameter `persistent:=true` which then tries to connect to a mongodb in order to save to and read from it.
### New features:
- Knowledge (i.e. instances, facts, functions, and goals) is stores in mongodb
- Knowledge is read from mongodb when requested
- Knowledge base can be started in persistent or non persistent mode
  - Based on parameter `/rosplan/knowledge_base/persistent` which is exposed in the launch files as `persistent`, e.g.: `roslaunch rosplan_planning_system planning_system_knowledge.launch persistent:=true`
  - Non persistent mode runs exactly the same as before
- DB parameters are exposed via ros parameters (design matching the current design of the other parameters, meaning global params instead of private ones):
  - Host: `/rosplan/db_host` exposed in launch files as: `db_host` _default_: `localhost`
  - Port: `/rosplan/db_port` exposed in launch files as: `db_port` _default_: `62345`
  - Name: `/rosplan/db_name` exposed in launch files as: `db_name`  _default_: `kcl_knowledge_base`
### Changes made to existing code:

I tried to find the least invasive method of implementing this. The persistent knowledge base just inherits from the knowledge base and overrides the functionality that has changed. The actual class to be used is decided at runtime using the `persistent` parameter as a flag. If the required `mongo-cxx-driver` cannot be found it compiles it without the persistent bit. Still a few changes to the original code had to be made.
- The main function has been moved into a `main.cpp`
  - The class (persistent/non-persistent) is selected at start-up.
- All the functions in `KnowledgeBase.h` have been declared `virtual` in order to override them.
  - The `private` functions also have been made `protected` for the same reason.
- The `CMakeLists.txt` has been adapted to allow for the compilation of the persistent version if `mongo-cxx-driver` is found
  - Also `mongodb_store` has been removed from the dependencies because it is not used.

Also pinging @pet1330 in case he wants to use this as well.

### CODE REVIEW

**Review by marc-hanheide — APPROVED** [review]

**Review by marc-hanheide — APPROVED** [review]
This looks very good to me. Eventually we should push this all upstream I guess.

**Comment by marc-hanheide** [comment]
See https://github.com/KCL-Planning/ROSPlan/pull/31 for the upstream PR that is still contributed to.

**Comment by marc-hanheide** [comment]
I have also triggered a re-release

**Comment by cdondrup** [comment]
Thank you.

**Pull request merged**
